### ISSUE TITLE
Circular import in `pyscfad.lib`

### ISSUE THREAD

**Issue by shivupa** [fishjojo/pyscfad#6]
Hi I'm excited to play around with this, but I tried running the oomp2 example in the provided docker image (thanks for providing that).

However I am finding that there seems to be a circular import somewhere in `lib`.
```
root@1d60b4045f1f:~# python 10-oomp2.py
Traceback (most recent call last):
  File "10-oomp2.py", line 5, in <module>
    from pyscfad.lib import numpy as np
  File "/usr/local/lib/python3.8/site-packages/pyscfad/lib/__init__.py", line 1, in <module>
    from pyscf.lib import ops
  File "/usr/local/lib/python3.8/site-packages/pyscf/lib/__init__.py", line 25, in <module>
    from pyscf.lib import linalg_helper
  File "/usr/local/lib/python3.8/site-packages/pyscf/lib/linalg_helper.py", line 30, in <module>
    from pyscf import scipy as pyscf_scipy
  File "/usr/local/lib/python3.8/site-packages/pyscf/scipy/__init__.py", line 4, in <module>
    from . import linalg
  File "/usr/local/lib/python3.8/site-packages/pyscf/scipy/linalg.py", line 4, in <module>
    from ._src.linalg import *
  File "/usr/local/lib/python3.8/site-packages/pyscf/scipy/_src/linalg.py", line 13, in <module>
    from ._pyscfad_linalg import *
  File "/usr/local/lib/python3.8/site-packages/pyscf/scipy/_src/_pyscfad_linalg.py", line 9, in <module>
    from pyscfad.lib.linalg_helper import eigh
  File "/usr/local/lib/python3.8/site-packages/pyscfad/lib/linalg_helper.py", line 6, in <module>
    from pyscfad.lib import ops, custom_jvp, jit
ImportError: cannot import name 'custom_jvp' from partially initialized module 'pyscfad.lib' (most likely due to a circular import) (/usr/local/lib/python3.8/site-packages/pyscfad/lib/__init__.py)
```

Any advice would be appreciated.

**Comment by fishjojo** [comment]
The example has been updated now in [8cbdd2b](https://github.com/fishjojo/pyscfad/commit/8cbdd2bfe5d69e1f5e96913ee881822c0f91d51a).

**Comment by shivupa** [comment]
Thanks! This works for me
